version: "3.8"
services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
  n8n:
    build:
      context: .
      dockerfile: Dockerfile_n8n
    ports:
      - "5678:5678"
    depends_on:
      - ollama
    environment:
      N8N_HOST: "0.0.0.0"
      OLLAMA_BASE_URL: "http://ollama:11434"
volumes:
  ollama: